// flow-typed signature: dc25f75241920ecab0c3043acde7bae1
// flow-typed version: <<STUB>>/babel-preset-joblift_v^3.3.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-joblift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-joblift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-joblift/index' {
  declare module.exports: $Exports<'babel-preset-joblift'>;
}
declare module 'babel-preset-joblift/index.js' {
  declare module.exports: $Exports<'babel-preset-joblift'>;
}
