// flow-typed signature: a6a0c4d55aa3770b5bfa0b576b203fd3
// flow-typed version: <<STUB>>/@morlay/babel-preset_v3.0.x/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@morlay/babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@morlay/babel-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@morlay/babel-preset/index' {
  declare module.exports: $Exports<'@morlay/babel-preset'>;
}
declare module '@morlay/babel-preset/index.js' {
  declare module.exports: $Exports<'@morlay/babel-preset'>;
}
